transformations:
  - name: "policies_curated"
    source_table: "raw.policies"
    target_table: "curated.policies"
    mode: "merge"                           # overwrite | append | merge
    merge_strategy: "insert_update"         # insert_update | insert_only | update_only | full_refresh
    streaming:
      enabled: false
      checkpoint_path: "auto"
    rules:
      select_columns:
        - PolicyID
        - CustomerID
        - PolicyDate
        - Status
        - PremiumAmount
      rename_columns:
        PolicyID: policy_id
        CustomerID: customer_id
      drop_columns:
        - temp_flag
      derive_columns:
        policy_year: "year(PolicyDate)"
      filter: "Status IS NOT NULL"
      cast_columns:
        PremiumAmount: "DOUBLE"
      joins:
        - with: "crm.customers"
          alias: "c"
          on: "main.CustomerID = c.customer_id"
          how: "left"
          select_columns:
            - c.customer_name
      drop_duplicates:
        subset: ["policy_id", "customer_id"]
      standardize:
        normalize_column_names: true
        trim_strings: true
