landing_sources:
  - name: "policies_file"
    path: "abfss://landing@storageacct.dfs.core.windows.net/policies/"
    format: "csv"
    raw_table: "raw.policies"
    options:
      header: true
      inferSchema: true
    checkpoint_path: "auto"
    mode: "append"

    validations:
      file_name_pattern: ".*policies.*\\.csv"   # regex match
      required_columns:
        - PolicyID
        - CustID
        - DateIssued
        - PremAmt
      max_file_size_mb: 100
      max_files_per_batch: 20
