environment: test
databricks:
  cluster: test-cluster
  workspace_url: https://adb-1234567890.1.azuredatabricks.net
storage:
  container: cfp-test
  account: cfpstorage
alerts:
  email: test-alerts@cfp.com
